sylius_twig_hooks:
    hooks:
        'sylius_shop.account.address_book.create':
            breadcrumbs:
                template: '@SyliusShop/account/address_book/create/breadcrumbs.html.twig'

        'sylius_shop.account.address_book.create.content':
            form:
                component: 'sylius_shop:account:address:form'
                props:
                    form: '@=_context.form'
                    resource: '@=_context.address'
                    template: '@SyliusShop/account/address_book/form/form.html.twig'

        'sylius_shop.account.address_book.create.content.header':
            title:
                template: '@SyliusShop/account/address_book/create/content/header/title.html.twig'
            subtitle:
                template: '@SyliusShop/account/address_book/create/content/header/subtitle.html.twig'

        'sylius_shop.account.address_book.create.content.form':
            fields:
                template: '@SyliusShop/account/address_book/common/content/form/fields.html.twig'
            buttons:
                template: '@SyliusShop/account/address_book/common/content/form/buttons.html.twig'

        'sylius_shop.account.address_book.create.content.form.buttons':
            add:
                template: '@SyliusShop/account/address_book/create/content/form/buttons/add.html.twig'
            cancel:
                template: '@SyliusShop/account/address_book/common/content/form/buttons/cancel.html.twig'
