sylius_twig_hooks:
    hooks:
        'sylius_shop.account.address_book.index.layout':
            breadcrumbs:
                template: '@SyliusShop/shared/account/address_book/layout/breadcrumbs.html.twig'

        'sylius_shop.account.address_book.index.layout.content':
            buttons:
                template: '@SyliusShop/account/address_book/index/layout/content/buttons.html.twig'
            addresses:
                template: '@SyliusShop/account/address_book/index/layout/content/addresses.html.twig'

        'sylius_shop.account.address_book.index.layout.content.buttons':
            add_address:
                template: '@SyliusShop/account/address_book/index/layout/content/buttons/add_address.html.twig'

        'sylius_shop.account.address_book.index.layout.content.addresses':
            default:
                template: '@SyliusShop/account/address_book/index/layout/content/addresses/default.html.twig'
            list:
                template: '@SyliusShop/account/address_book/index/layout/content/addresses/list.html.twig'

        'sylius_shop.account.address_book.index.layout.content.addresses.default':
            badge:
                template: '@SyliusShop/account/address_book/index/layout/content/addresses/default/badge.html.twig'
            content:
                template: '@SyliusShop/shared/account/address_book/index/layout/content/address/content.html.twig'
            actions:
                template: '@SyliusShop/shared/account/address_book/index/layout/content/address/actions.html.twig'

        'sylius_shop.account.address_book.index.layout.content.addresses.default.actions':
            edit:
                template: '@SyliusShop/shared/account/address_book/index/layout/content/address/actions/edit.html.twig'
            delete:
                template: '@SyliusShop/shared/account/address_book/index/layout/content/address/actions/delete.html.twig'

        'sylius_shop.account.address_book.index.layout.content.addresses.list':
            address:
                template: '@SyliusShop/account/address_book/index/layout/content/addresses/list/address.html.twig'

        'sylius_shop.account.address_book.index.layout.content.addresses.list.address':
            content:
                template: '@SyliusShop/shared/account/address_book/index/layout/content/address/content.html.twig'
            actions:
                template: '@SyliusShop/shared/account/address_book/index/layout/content/address/actions.html.twig'

        'sylius_shop.account.address_book.index.layout.content.addresses.list.address.actions':
            edit:
                template: '@SyliusShop/shared/account/address_book/index/layout/content/address/actions/edit.html.twig'
            delete:
                template: '@SyliusShop/shared/account/address_book/index/layout/content/address/actions/delete.html.twig'
            set_default:
                component: 'sylius_shop:account:address:default_form'
                props:
                    customer: '@=_context.customer'
                    template: '@SyliusShop/account/address_book/set_as_default.html.twig'
