sylius_twig_hooks:
    hooks:
        'sylius_shop.account.address_book.update.layout':
            breadcrumbs:
                template: '@SyliusShop/shared/account/address_book/layout/breadcrumbs.html.twig'

        'sylius_shop.account.address_book.update.layout.content':
            form:
                component: 'sylius_shop:account:address:form'
                props:
                    form: '@=_context.form'
                    resource: '@=_context.address'
                    template: '@SyliusShop/account/address_book/form/form.html.twig'
                configuration:
                    method: 'PUT'

        'sylius_shop.account.address_book.update.layout.content.header':
            title:
                template: '@SyliusShop/account/address_book/form/update/layout/content/header/title.html.twig'
            subtitle:
                template: '@SyliusShop/account/address_book/form/update/layout/content/header/subtitle.html.twig'

        'sylius_shop.account.address_book.update.layout.content.form':
            fields:
                template: '@SyliusShop/shared/account/address_book/form/fields.html.twig'
            buttons:
                template: '@SyliusShop/shared/account/address_book/form/buttons.html.twig'

        'sylius_shop.account.address_book.update.layout.content.form.buttons':
            save:
                template: '@SyliusShop/account/address_book/form/update/layout/content/buttons/save.html.twig'
            cancel:
                template: '@SyliusShop/shared/account/address_book/form/buttons/cancel.html.twig'
