# Dockerfile for Railway deployment
# Railway uses sylius/ as build context (Dockerfile location)
# This Dockerfile copies from current directory (sylius/)
# Updated: 2025-12-06 - Using temp copy approach for all directories
# Build ID: ae9e8904c2 - Force rebuild - Railway cache issue
# IMPORTANT: This Dockerfile uses COPY . /tmp/all-files then extracts directories
# DO NOT use direct COPY commands for directories - they fail on Railway
FROM php:8.2-apache

# Install required PHP extensions and tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    libzip-dev \
    libicu-dev \
    libxml2-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libsqlite3-dev \
    sqlite3 \
    libonig-dev \
    pkg-config \
    zip \
    unzip \
    git \
    curl \
    ca-certificates \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH \
    && docker-php-ext-configure pdo_sqlite --with-pdo-sqlite=/usr \
    && docker-php-ext-install -j$(nproc) zip pdo pdo_sqlite intl xml gd mbstring opcache \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Enable Apache mod_rewrite
RUN a2enmod rewrite

# Configure PHP for production with memory optimization (optimized for 2GB Standard plan)
# Using 128M limit to leave room for system processes
RUN echo 'memory_limit = 128M' > /usr/local/etc/php/conf.d/memory.ini && \
    echo 'post_max_size = 10M' >> /usr/local/etc/php/conf.d/memory.ini && \
    echo 'upload_max_filesize = 10M' >> /usr/local/etc/php/conf.d/memory.ini && \
    echo 'realpath_cache_size = 4096K' >> /usr/local/etc/php/conf.d/memory.ini && \
    echo 'realpath_cache_ttl = 600' >> /usr/local/etc/php/conf.d/memory.ini && \
    echo 'max_execution_time = 300' >> /usr/local/etc/php/conf.d/memory.ini && \
    echo 'max_input_time = 300' >> /usr/local/etc/php/conf.d/memory.ini && \
    echo 'opcache.enable=1' > /usr/local/etc/php/conf.d/opcache.ini && \
    echo 'opcache.enable_cli=0' >> /usr/local/etc/php/conf.d/opcache.ini && \
    echo 'opcache.memory_consumption=64' >> /usr/local/etc/php/conf.d/opcache.ini && \
    echo 'opcache.interned_strings_buffer=8' >> /usr/local/etc/php/conf.d/opcache.ini && \
    echo 'opcache.max_accelerated_files=5000' >> /usr/local/etc/php/conf.d/opcache.ini && \
    echo 'opcache.validate_timestamps=0' >> /usr/local/etc/php/conf.d/opcache.ini && \
    echo 'opcache.save_comments=1' >> /usr/local/etc/php/conf.d/opcache.ini && \
    echo 'opcache.fast_shutdown=1' >> /usr/local/etc/php/conf.d/opcache.ini && \
    echo 'opcache.revalidate_freq=0' >> /usr/local/etc/php/conf.d/opcache.ini

# Set working directory
WORKDIR /var/www/html

# Install Composer (must be BEFORE any 'composer' commands)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy composer file for caching
# Railway uses sylius/ as build context (Dockerfile location), so copy from current directory
COPY composer.json ./composer.json

# Install deps (allow scripts for Symfony Runtime)
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV APP_ENV=prod
ENV APP_DEBUG=0
ENV DATABASE_URL=sqlite:////var/www/html/var/data.db
ENV SYMFONY_ENV=prod
ENV PHP_MEMORY_LIMIT=128M
ENV SYMFONY_CACHE_WARMUP=0
# Install without scripts first to avoid symfony-cmd issues
RUN composer install --no-dev --optimize-autoloader --no-scripts --no-interaction --prefer-dist --ignore-platform-reqs
# Generate autoload_runtime.php manually if it doesn't exist (Symfony Runtime requirement)
# This file is normally generated by symfony/runtime composer scripts
# Note: We'll load index.php.original (created later) to avoid circular reference
RUN cat > vendor/autoload_runtime.php << 'EOF'
<?php

// Ensure autoloader is loaded before anything else
require_once __DIR__."/autoload.php";

return function (array $context = []) {
    if (!isset($context["APP_ENV"])) {
        throw new RuntimeException("Please provide \"APP_ENV\" environment variable.");
    }
    $_SERVER["APP_ENV"] = $_ENV["APP_ENV"] = $context["APP_ENV"];
    $_SERVER["APP_DEBUG"] = $_SERVER["APP_DEBUG"] ?? $_ENV["APP_DEBUG"] ?? "prod" !== $context["APP_ENV"];
    $_SERVER["APP_DEBUG"] = $_ENV["APP_DEBUG"] = (int) $_SERVER["APP_DEBUG"] || ("prod" !== $context["APP_ENV"]);
    
    // Load index.php.original (the original Kernel factory) instead of index.php (our bootstrap)
    $indexFile = file_exists(__DIR__."/../public/index.php.original") 
        ? __DIR__."/../public/index.php.original" 
        : __DIR__."/../public/index.php";
    
    $runtime = require $indexFile;
    return $runtime($context);
};
EOF
# Verify autoload_runtime.php exists
RUN test -f vendor/autoload_runtime.php || (echo "ERROR: Failed to create autoload_runtime.php" && exit 1)

# Copy the rest of the app (vendor will persist since it's not in source)
# Railway uses sylius/ as build context (Dockerfile location), so copy from current directory
# Preserve vendor directory by moving it temporarily, then restoring after COPY
RUN mv vendor vendor-temp 2>/dev/null || true
# CRITICAL: Railway's build context is not including directories properly
# Copy everything to temp first, then extract all directories we need
# This ensures we get all files even if direct COPY fails
COPY . /tmp/all-files
# Debug: Check what's in the build context - THIS MUST RUN
RUN echo "=== DEBUG: What's in /tmp/all-files? ===" && \
    echo "Current directory:" && pwd && \
    echo "Listing /tmp/all-files:" && \
    ls -la /tmp/all-files/ | head -30 && \
    echo "=== Checking for essential directories ===" && \
    (test -d /tmp/all-files/public && echo "✓ public/ EXISTS in build context" && echo "Contents:" && ls -la /tmp/all-files/public/ | head -10) || echo "✗ public/ MISSING in build context" && \
    (test -d /tmp/all-files/src && echo "✓ src/ EXISTS in build context" && echo "Contents:" && ls -la /tmp/all-files/src/ | head -10) || echo "✗ src/ MISSING in build context" && \
    (test -d /tmp/all-files/config && echo "✓ config/ EXISTS in build context" && echo "Contents:" && ls -la /tmp/all-files/config/ | head -10) || echo "✗ config/ MISSING in build context" && \
    echo "=== End DEBUG ==="
# Ensure all directories exist
RUN mkdir -p ./public ./src ./config ./templates ./assets ./bin ./translations
# Copy all essential and optional directories from temp location
# The application code should be at root level, but Railway's build context might not include it
# Check both root level and Sylius/ subdirectory
RUN echo "=== Copying directories from build context ===" && \
    echo "Checking root level first..." && \
    (test -d /tmp/all-files/public && echo "✓ public/ EXISTS at root" && ls -la /tmp/all-files/public/ | head -5) || echo "✗ public/ MISSING at root" && \
    (test -d /tmp/all-files/src && echo "✓ src/ EXISTS at root" && ls -la /tmp/all-files/src/ | head -5) || echo "✗ src/ MISSING at root" && \
    (test -d /tmp/all-files/config && echo "✓ config/ EXISTS at root" && ls -la /tmp/all-files/config/ | head -5) || echo "✗ config/ MISSING at root" && \
    echo "Checking Sylius/ subdirectory..." && \
    (test -d /tmp/all-files/Sylius && echo "✓ Sylius/ EXISTS" && ls -la /tmp/all-files/Sylius/ | head -5) || echo "✗ Sylius/ MISSING" && \
    echo "Attempting to copy from root level first..." && \
    if [ -d /tmp/all-files/public ] && [ "$(ls -A /tmp/all-files/public 2>/dev/null)" ]; then \
        echo "Found public/ at root, copying..." && \
        cp -rv /tmp/all-files/public/* ./public/ 2>&1 && \
        echo "public/ copied successfully" && \
        ls -la ./public/ | head -10; \
    elif [ -d /tmp/all-files/Sylius/public ] && [ "$(ls -A /tmp/all-files/Sylius/public 2>/dev/null)" ]; then \
        echo "Found public/ in Sylius/, copying..." && \
        cp -rv /tmp/all-files/Sylius/public/* ./public/ 2>&1 && \
        echo "public/ copied successfully"; \
    else \
        echo "ERROR: public/ not found at root or in Sylius/!" && \
        echo "Full contents of /tmp/all-files:" && \
        find /tmp/all-files -maxdepth 2 -type d | head -20 && \
        exit 1; \
    fi && \
    if [ -d /tmp/all-files/src ] && [ "$(ls -A /tmp/all-files/src 2>/dev/null)" ]; then \
        echo "Found src/ at root, copying..." && \
        cp -rv /tmp/all-files/src/* ./src/ 2>&1 && \
        echo "src/ copied successfully" && \
        ls -la ./src/ | head -10; \
    elif [ -d /tmp/all-files/Sylius/src ] && [ "$(ls -A /tmp/all-files/Sylius/src 2>/dev/null)" ]; then \
        echo "Found src/ in Sylius/, copying..." && \
        cp -rv /tmp/all-files/Sylius/src/* ./src/ 2>&1 && \
        echo "src/ copied successfully"; \
    else \
        echo "ERROR: src/ not found at root or in Sylius/!" && exit 1; \
    fi && \
    if [ -d /tmp/all-files/config ] && [ "$(ls -A /tmp/all-files/config 2>/dev/null)" ]; then \
        echo "Found config/ at root, copying..." && \
        cp -rv /tmp/all-files/config/* ./config/ 2>&1 && \
        echo "config/ copied successfully" && \
        ls -la ./config/ | head -10; \
    elif [ -d /tmp/all-files/Sylius/config ] && [ "$(ls -A /tmp/all-files/Sylius/config 2>/dev/null)" ]; then \
        echo "Found config/ in Sylius/, copying..." && \
        cp -rv /tmp/all-files/Sylius/config/* ./config/ 2>&1 && \
        echo "config/ copied successfully"; \
    else \
        echo "ERROR: config/ not found at root or in Sylius/!" && exit 1; \
    fi && \
    # Copy optional directories from Sylius/ subdirectory
    if [ -d /tmp/all-files/Sylius/templates ] && [ "$(ls -A /tmp/all-files/Sylius/templates 2>/dev/null)" ]; then \
        echo "Found Sylius/templates/, copying..." && \
        cp -r /tmp/all-files/Sylius/templates/* ./templates/ 2>/dev/null || true && \
        echo "templates/ copied successfully"; \
    else \
        echo "templates/ directory not found - using empty directory"; \
    fi && \
    if [ -d /tmp/all-files/Sylius/assets ] && [ "$(ls -A /tmp/all-files/Sylius/assets 2>/dev/null)" ]; then \
        echo "Found Sylius/assets/, copying..." && \
        cp -r /tmp/all-files/Sylius/assets/* ./assets/ 2>/dev/null || true && \
        echo "assets/ copied successfully"; \
    else \
        echo "assets/ directory not found - using empty directory"; \
    fi && \
    if [ -d /tmp/all-files/Sylius/bin ] && [ "$(ls -A /tmp/all-files/Sylius/bin 2>/dev/null)" ]; then \
        echo "Found Sylius/bin/, copying..." && \
        cp -r /tmp/all-files/Sylius/bin/* ./bin/ 2>/dev/null || true && \
        echo "bin/ copied successfully"; \
    else \
        echo "bin/ directory not found - using empty directory"; \
    fi && \
    if [ -d /tmp/all-files/Sylius/translations ] && [ "$(ls -A /tmp/all-files/Sylius/translations 2>/dev/null)" ]; then \
        echo "Found Sylius/translations/, copying..." && \
        cp -r /tmp/all-files/Sylius/translations/* ./translations/ 2>/dev/null || true && \
        echo "translations/ copied successfully"; \
    else \
        echo "translations/ directory not found - using empty directory"; \
    fi && \
    echo "=== Listing what was copied ===" && \
    ls -la /tmp/all-files/ | head -20 && \
    echo "=== Cleaning up temp files ===" && \
    rm -rf /tmp/all-files
# Debug: Verify what was copied
RUN echo "=== Verification after explicit COPY ===" && \
    echo "public/ contents:" && (ls -la public/ | head -10 || echo "public/ is empty") && \
    echo "src/ status:" && (test -d src && [ "$(ls -A src 2>/dev/null)" ] && echo "src/ EXISTS with files" && ls -la src/ | head -5 || echo "src/ missing or empty") && \
    echo "config/ status:" && (test -d config && [ "$(ls -A config 2>/dev/null)" ] && echo "config/ EXISTS with files" && ls -la config/ | head -5 || echo "config/ missing or empty")
# Verify what we have after copy - this MUST show in logs
RUN echo "=== VERIFICATION: After copying from Sylius/ ===" && \
    echo "public/ contents:" && (ls -la public/ | head -10 || echo "public/ is empty or missing") && \
    echo "src/ status:" && (test -d src && test "$(ls -A src 2>/dev/null)" && echo "src/ EXISTS and has files" || echo "src/ missing or empty") && \
    echo "config/ contents:" && (ls -la config/ | head -10 || echo "config/ is empty or missing")
# Remove unnecessary files/directories that were copied but we don't need
# Keep README.md but remove other markdown files
RUN find . -maxdepth 1 -name "*.md" ! -name "README.md" -delete 2>/dev/null || true && \
    rm -rf tests features docs .git .gitignore Sylius 2>/dev/null || true
# Root-level files (like .md, .php scripts) are not critical for runtime, skip them
# Restore vendor directory (we installed it earlier, don't overwrite with empty one from source)
RUN if [ -d vendor-temp ]; then rm -rf vendor 2>/dev/null || true && mv vendor-temp vendor; fi
RUN test -d vendor || (echo "ERROR: vendor directory missing" && exit 1)
# Create minimal bin/console if bin directory wasn't copied
# Symfony will regenerate this during installation if needed
RUN mkdir -p ./bin && \
    echo '#!/usr/bin/env php' > ./bin/console && \
    echo '<?php' >> ./bin/console && \
    echo 'require __DIR__."/../vendor/autoload.php";' >> ./bin/console && \
    echo 'use Symfony\Bundle\FrameworkBundle\Console\Application;' >> ./bin/console && \
    echo '$kernel = new App\Kernel($_SERVER["APP_ENV"] ?? "prod", (bool)($_SERVER["APP_DEBUG"] ?? false));' >> ./bin/console && \
    echo '$application = new Application($kernel);' >> ./bin/console && \
    echo '$application->run();' >> ./bin/console && \
    chmod +x ./bin/console
# Verify vendor still exists after copy
RUN ls -la vendor/autoload_runtime.php || (echo "ERROR: vendor/autoload_runtime.php missing after COPY" && exit 1)

# Verify critical application files exist
# First check what we actually have
RUN echo "=== VERIFICATION: Checking application structure ===" && \
    echo "Working directory:" && pwd && \
    echo "=== All directories ===" && \
    ls -la /var/www/html/ | head -25 && \
    echo "=== public/ directory ===" && \
    (test -d /var/www/html/public && echo "public/ EXISTS" && ls -la /var/www/html/public/ | head -10) || echo "public/ MISSING" && \
    echo "=== src/ directory ===" && \
    (test -d /var/www/html/src && echo "src/ EXISTS" && ls -la /var/www/html/src/ | head -10) || echo "src/ MISSING" && \
    echo "=== config/ directory ===" && \
    (test -d /var/www/html/config && echo "config/ EXISTS" && ls -la /var/www/html/config/ | head -10) || echo "config/ MISSING" && \
    echo "=== Checking for Sylius/ ===" && \
    (test -d /var/www/html/Sylius && echo "Sylius/ STILL EXISTS" && ls -la /var/www/html/Sylius/ | head -5) || echo "Sylius/ removed or never existed"
# Now run the actual tests with absolute paths
RUN cd /var/www/html && \
    test -d public || (echo "ERROR: public directory missing" && exit 1) && \
    test -f public/index.php || (echo "ERROR: public/index.php missing - public/ exists but is empty!" && ls -la public/ && exit 1) && \
    test -d src || (echo "ERROR: src directory missing" && exit 1) && \
    test -d config || (echo "ERROR: config directory missing" && exit 1) && \
    echo "Application structure verified"

# Create necessary directories and set permissions
# Clear any stale cache from source - this is critical for production
RUN rm -rf var/cache var/log var/sessions var/data.db || true
RUN mkdir -p var/cache/prod var/log var/sessions \
    && chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html \
    && chmod -R 777 var/ \
    && touch var/data.db \
    && chown www-data:www-data var/data.db \
    && chmod 666 var/data.db

# Fix Doctrine cache configuration to avoid CacheAdapter issue
# Override the prod doctrine config to use Symfony cache directly
RUN cat > config/packages/prod/doctrine.yaml << 'DOCTRINEEOF'
doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                result_cache_driver:
                    type: pool
                    pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem
DOCTRINEEOF

# Configure Apache for Sylius - minimal changes
ENV APACHE_DOCUMENT_ROOT /var/www/html/public

# Update the default virtual host to use our document root (use actual path in RUN)
RUN sed -ri -e 's|DocumentRoot /var/www/html|DocumentRoot /var/www/html/public|g' /etc/apache2/sites-available/*.conf \
    && echo '<Directory /var/www/html/public>' >> /etc/apache2/apache2.conf \
    && echo '    Options Indexes FollowSymLinks' >> /etc/apache2/apache2.conf \
    && echo '    AllowOverride All' >> /etc/apache2/apache2.conf \
    && echo '    Require all granted' >> /etc/apache2/apache2.conf \
    && echo '</Directory>' >> /etc/apache2/apache2.conf

# Ensure .htaccess routing
RUN echo 'RewriteEngine On' > /var/www/html/public/.htaccess \
    && echo 'RewriteCond %{REQUEST_FILENAME} !-f' >> /var/www/html/public/.htaccess \
    && echo 'RewriteRule ^(.*)$ index.php [QSA,L]' >> /var/www/html/public/.htaccess

# Test Apache configuration before finalizing
RUN apachectl -t 2>&1 || (echo "=== Apache config test failed! ===" && cat /etc/apache2/apache2.conf | tail -30 && echo "=== End of config ===" && exit 1) && echo "Apache configuration test passed"

# Fix index.php to auto-execute when called via web (Symfony Runtime bootstrap)
# Create index.php.original with just the Kernel factory (no autoload_runtime.php require)
# since autoloader is already loaded by autoload_runtime.php
# Note: Kernel.php must be explicitly required since it's only in autoload-dev
RUN cat > /var/www/html/public/index.php.original << 'ORIGEOF'
<?php

declare(strict_types=1);

use App\Kernel;

// Autoloader is already loaded by autoload_runtime.php
// Explicitly require Kernel since it's only in autoload-dev and we're using --no-dev
require_once dirname(__DIR__).'/src/Kernel.php';

return static function (array $context) {
    return new Kernel($context['APP_ENV'], (bool) $context['APP_DEBUG']);
};
ORIGEOF

# Create a simple test file first to verify Apache works
RUN echo '<?php phpinfo(); ?>' > /var/www/html/public/test.php

# Create the bootstrap index.php
RUN cat > /var/www/html/public/index.php << 'EOF'
<?php

declare(strict_types=1);

// Prevent fatal errors from crashing Apache
register_shutdown_function(function() {
    $error = error_get_last();
    if ($error !== null && in_array($error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR])) {
        http_response_code(500);
        echo '<h1>Fatal Error</h1>';
        echo '<p><strong>Message:</strong> ' . htmlspecialchars($error['message']) . '</p>';
        echo '<p><strong>File:</strong> ' . htmlspecialchars($error['file']) . ':' . $error['line'] . '</p>';
        exit;
    }
});

// Enable error reporting
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

try {
    // Load autoloader first
    if (!file_exists(dirname(__DIR__).'/vendor/autoload.php')) {
        throw new RuntimeException('Composer autoloader not found. Run composer install.');
    }
    require_once dirname(__DIR__).'/vendor/autoload.php';

    // Load the runtime function
    if (!file_exists(dirname(__DIR__).'/vendor/autoload_runtime.php')) {
        throw new RuntimeException('autoload_runtime.php not found.');
    }
    $runtime = require dirname(__DIR__).'/vendor/autoload_runtime.php';

    $appEnv = $_ENV['APP_ENV'] ?? $_SERVER['APP_ENV'] ?? 'prod';
    $appDebug = (bool) ($_ENV['APP_DEBUG'] ?? $_SERVER['APP_DEBUG'] ?? '0');

    // The runtime function loads index.php.original and returns the Kernel
    $kernel = $runtime([
        'APP_ENV' => $appEnv,
        'APP_DEBUG' => $appDebug,
    ]);

    // Handle the request
    $request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
    $response = $kernel->handle($request);
    $response->send();
    $kernel->terminate($request, $response);
    
    // Clean up after request
    unset($request, $response, $kernel);
} catch (\Throwable $e) {
    // Display error details instead of crashing (with memory limit check)
    http_response_code(500);
    $memoryUsage = memory_get_usage(true) / 1024 / 1024;
    $memoryPeak = memory_get_peak_usage(true) / 1024 / 1024;
    echo '<h1>Error</h1>';
    echo '<p><strong>Memory Usage:</strong> ' . round($memoryUsage, 2) . ' MB / Peak: ' . round($memoryPeak, 2) . ' MB</p>';
    echo '<p><strong>Message:</strong> ' . htmlspecialchars($e->getMessage()) . '</p>';
    echo '<p><strong>File:</strong> ' . htmlspecialchars($e->getFile()) . ':' . $e->getLine() . '</p>';
    // Limit trace depth to prevent memory issues
    $trace = $e->getTrace();
    $trace = array_slice($trace, 0, 10); // Only show first 10 frames
    echo '<pre>' . htmlspecialchars($e->getMessage() . "\n" . print_r($trace, true)) . '</pre>';
    error_log('PHP Error: ' . $e->getMessage() . ' in ' . $e->getFile() . ':' . $e->getLine() . ' (Memory: ' . round($memoryUsage, 2) . 'MB)');
    // Clean up memory
    unset($trace, $e);
}
EOF

# Create startup script with logging and ensure database permissions
RUN echo '#!/bin/bash' > /entrypoint.sh && \
    echo 'echo "=== Starting SurfsUp Shop ==="' >> /entrypoint.sh && \
    echo '# Ensure var directory and database have proper permissions' >> /entrypoint.sh && \
    echo 'mkdir -p /var/www/html/var/cache/prod /var/www/html/var/log /var/www/html/var/sessions || true' >> /entrypoint.sh && \
    echo 'rm -f /var/www/html/var/data.db || true' >> /entrypoint.sh && \
    echo 'touch /var/www/html/var/data.db || true' >> /entrypoint.sh && \
    echo 'chown -R www-data:www-data /var/www/html/var || true' >> /entrypoint.sh && \
    echo 'chmod -R 777 /var/www/html/var || true' >> /entrypoint.sh && \
    echo 'chmod 666 /var/www/html/var/data.db || true' >> /entrypoint.sh && \
    echo 'echo "Database file permissions:"' >> /entrypoint.sh && \
    echo 'ls -la /var/www/html/var/data.db || echo "Database file not found"' >> /entrypoint.sh && \
    echo 'echo "Var directory permissions:"' >> /entrypoint.sh && \
    echo 'ls -ld /var/www/html/var || true' >> /entrypoint.sh && \
    echo 'echo "Testing Apache config..."' >> /entrypoint.sh && \
    echo 'apachectl -t 2>&1 || echo "WARNING: Apache config test had warnings"' >> /entrypoint.sh && \
    echo 'echo "Starting Apache..."' >> /entrypoint.sh && \
    echo 'exec apache2-foreground' >> /entrypoint.sh && \
    chmod +x /entrypoint.sh

EXPOSE 80
CMD ["/entrypoint.sh"]


