sylius_twig_hooks:
    hooks:
        'sylius_admin.order.history':
            sidebar:
                template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@SyliusAdmin/shared/crud/common/content.html.twig'
                priority: 0

        'sylius_admin.order.history.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
                priority: 200
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 100
            sections:
                template: '@SyliusAdmin/order/history/content/sections.html.twig'
                priority: 0

        'sylius_admin.order.history.content.header':
            breadcrumbs:
                template: '@SyliusAdmin/shared/crud/show/content/header/breadcrumbs.html.twig'
                configuration:
                    rendered_field_prefix: '#'
                    rendered_field: number
                    action: 'sylius.ui.history'
                priority: 100
            title_block:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block.html.twig'
                priority: 0

        'sylius_admin.order.history.content.header.title_block':
            title:
                template: '@SyliusAdmin/order/history/content/header/title_block/title.html.twig'
                priority: 100
            actions:
                template: '@SyliusAdmin/order/history/content/header/title_block/actions.html.twig'
                priority: 0

        'sylius_admin.order.history.content.header.title_block.actions':
            back:
                template: '@SyliusAdmin/order/history/content/header/title_block/actions/back.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections':
            addresses:
                template: '@SyliusAdmin/order/history/content/sections/addresses.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.addresses':
            billing_address:
                component: sylius_admin:order:address_history
                props:
                    addressId: '@=_context.resource.getBillingAddress().getId()'
                    header: 'sylius.ui.billing_address'
                    sort: 'desc'
                    template: '@SyliusAdmin/order/history/content/sections/addresses/billing_address.html.twig'
                priority: 100
            shipping_address:
                component: sylius_admin:order:address_history
                props:
                    addressId: '@=_context.resource.getShippingAddress().getId()'
                    header: 'sylius.ui.shipping_address'
                    sort: 'desc'
                    template: '@SyliusAdmin/order/history/content/sections/addresses/shipping_address.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.addresses.billing_address':
            header: 
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/header.html.twig'
                priority: 100
            details:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.addresses.billing_address.header':
            title:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/header/title.html.twig'
                priority: 0
                
        'sylius_admin.order.history.content.sections.addresses.billing_address.details':
            modification_status:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/modification_status.html.twig'
                priority: 100
            data:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/data.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.addresses.billing_address.details.modification_status':
            label:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/label.html.twig'
                priority: 100
            logged:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/logged.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.addresses.billing_address.details.data':
            first_name:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/first_name.html.twig'
                priority: 900
            last_name:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/last_name.html.twig'
                priority: 800
            phone_number:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/phone_number.html.twig'
                priority: 700
            street:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/street.html.twig'
                priority: 600
            company:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/company.html.twig'
                priority: 500
            city:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/city.html.twig'
                priority: 400
            postcode:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/postcode.html.twig'
                priority: 300
            country_code:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/country_code.html.twig'
                priority: 200
            province_code:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/province_code.html.twig'
                priority: 100
            province_name:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/province_name.html.twig'
                priority: 0

        'sylius_admin.order.history.content.sections.addresses.shipping_address':
            header:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/header.html.twig'
                priority: 200
            details:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details.html.twig'
                priority: 100
        
        'sylius_admin.order.history.content.sections.addresses.shipping_address.header':
            title:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/header/title.html.twig'
                priority: 0
        
        'sylius_admin.order.history.content.sections.addresses.shipping_address.details':
            modification_status:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/modification_status.html.twig'
                priority: 100
            data:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/data.html.twig'
                priority: 0
        
        'sylius_admin.order.history.content.sections.addresses.shipping_address.details.modification_status':
            label:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/label.html.twig'
                priority: 100
            logged:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/logged.html.twig'
                priority: 0
        
        'sylius_admin.order.history.content.sections.addresses.shipping_address.details.data':
            first_name:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/first_name.html.twig'
                priority: 900
            last_name:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/last_name.html.twig'
                priority: 800
            phone_number:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/phone_number.html.twig'
                priority: 700
            street:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/street.html.twig'
                priority: 600
            company:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/company.html.twig'
                priority: 500
            city:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/city.html.twig'
                priority: 400
            postcode:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/postcode.html.twig'
                priority: 300
            country_code:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/country_code.html.twig'
                priority: 200
            province_code:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/province_code.html.twig'
                priority: 100
            province_name:
                template: '@SyliusAdmin/order/history/common/sections/addresses/address/details/province_name.html.twig'
                priority: 0

