sylius_twig_hooks:
    hooks:
        'sylius_shop.account.order.show.layout':
            breadcrumbs:
                template: '@SyliusShop/account/order/show/layout/breadcrumbs.html.twig'

        'sylius_shop.account.order.show.layout.content':
            summary:
                template: "@SyliusShop/account/order/show/layout/content/summary.html.twig"

        'sylius_shop.account.order.show.layout.content.header':
            buttons:
                template: "@SyliusShop/account/order/show/layout/content/header/buttons.html.twig"
            details:
                template: "@SyliusShop/account/order/show/layout/content/header/details.html.twig"

        'sylius_shop.account.order.show.layout.content.header.details':
            state:
                template: "@SyliusShop/account/order/show/layout/content/header/details/state.html.twig"
            completed_at:
                template: "@SyliusShop/account/order/show/layout/content/header/details/completed_at.html.twig"
            currency:
                template: "@SyliusShop/account/order/show/layout/content/header/details/currency.html.twig"
