sylius_twig_hooks:
    hooks:
        'sylius_shop.account.order.show':
            breadcrumbs:
                template: '@SyliusShop/account/order/show/breadcrumbs.html.twig'

        'sylius_shop.account.order.show.content':
            summary:
                template: "@SyliusShop/account/order/show/content/summary.html.twig"

        'sylius_shop.account.order.show.content.header':
            title:
                template: "@SyliusShop/account/order/show/content/header/title.html.twig"
            buttons:
                template: "@SyliusShop/account/order/show/content/header/buttons.html.twig"
            details:
                template: "@SyliusShop/account/order/show/content/header/details.html.twig"

        'sylius_shop.account.order.show.content.header.details':
            state:
                template: "@SyliusShop/account/order/show/content/header/details/state.html.twig"
            completed_at:
                template: "@SyliusShop/account/order/show/content/header/details/completed_at.html.twig"
            currency:
                template: "@SyliusShop/account/order/show/content/header/details/currency.html.twig"
