# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

default:
    suites:
        api_viewing_product_in_admin_panel:
            contexts:
                - sylius.behat.context.hook.doctrine_orm

                - sylius.behat.context.transform.channel
                - sylius.behat.context.transform.lexical
                - sylius.behat.context.transform.product
                - sylius.behat.context.transform.product_option
                - sylius.behat.context.transform.taxon

                - sylius.behat.context.setup.admin_api_security
                - sylius.behat.context.setup.channel
                - sylius.behat.context.setup.product
                - sylius.behat.context.setup.product_association
                - sylius.behat.context.setup.product_option
                - sylius.behat.context.setup.shipping_category
                - sylius.behat.context.setup.taxonomy

                - sylius.behat.context.api.admin.managing_products

            filters:
                tags: "@viewing_product_in_admin_panel&&@api"
            javascript: false
