sylius_twig_hooks:
    hooks:
        'sylius_shop.account.change_password.layout':
            breadcrumbs:
                template: '@SyliusShop/account/change_password/layout/breadcrumbs.html.twig'

        'sylius_shop.account.change_password.layout.content':
            form:
                component: 'sylius_shop:account:change_password_form'
                props:
                    form: '@=_context.form'
                    template: '@SyliusShop/account/change_password/layout/content/form.html.twig'

        'sylius_shop.account.change_password.layout.content.header':
            title:
                template: '@SyliusShop/account/change_password/layout/content/header/title.html.twig'
            subtitle:
                template: '@SyliusShop/account/change_password/layout/content/header/subtitle.html.twig'

        'sylius_shop.account.change_password.layout.content.form':
            fields:
                template: '@SyliusShop/account/change_password/layout/content/form/fields.html.twig'
            buttons:
                template: '@SyliusShop/account/change_password/layout/content/form/buttons.html.twig'

        'sylius_shop.account.change_password.layout.content.form.fields':
            current_password:
                template: '@SyliusShop/account/change_password/layout/content/form/fields/current_password.html.twig'
            new_password:
                template: '@SyliusShop/account/change_password/layout/content/form/fields/new_password.html.twig'
            confirm_new_password:
                template: '@SyliusShop/account/change_password/layout/content/form/fields/confirm_new_password.html.twig'

        'sylius_shop.account.change_password.layout.content.form.buttons':
            submit:
                template: '@SyliusShop/account/change_password/layout/content/form/buttons/submit.html.twig'
